### ISSUE TITLE
Lacks build instructions / cannot build in VSC

### ISSUE THREAD

**Issue by g0lgs** [shane-powell/pico-display-colour-change#1]
I have failed to get this to build in VSC.

![image](https://user-images.githubusercontent.com/64634584/105996603-7b07a880-60a2-11eb-922b-84ef6e4d2251.png)

**Comment by shane-powell** [comment]
Just pushed a fix. Pimoroni updated the SDK changing `point` to `Point`.

**Comment by shane-powell** [comment]
I have also added the build steps from the Pimoroni boilerplate. This was created before the the boilerplate was turned into a proper GitHub template.
